language: java
gradle : check
jdk: oraclejdk8


addons:
  sonarcloud:
    organization: "kumarabhishek0809"
    token:
      secure: "**************************" # encrypted value of your token

script:
  - ./gradlew sonarqube
