//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.29 at 01:52:13 PM GST 
//


package sdf;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EstablishmentAddressDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EstablishmentAddressDetail">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="areaId" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="cityId" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="emirateId" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="emiratesDepartmentId" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="poBoxEmirateId" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="poBoxNo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="flatNo" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="faxNo" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="street" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="email" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="mobileNo" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="officeNo" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="telephoneNo" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="building" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EstablishmentAddressDetail")
public class EstablishmentAddressDetail {

    @XmlAttribute(name = "areaId", required = true)
    protected long areaId;
    @XmlAttribute(name = "cityId", required = true)
    protected long cityId;
    @XmlAttribute(name = "emirateId", required = true)
    protected long emirateId;
    @XmlAttribute(name = "emiratesDepartmentId", required = true)
    protected long emiratesDepartmentId;
    @XmlAttribute(name = "poBoxEmirateId", required = true)
    protected long poBoxEmirateId;
    @XmlAttribute(name = "poBoxNo")
    protected String poBoxNo;
    @XmlAttribute(name = "flatNo", required = true)
    protected String flatNo;
    @XmlAttribute(name = "faxNo", required = true)
    protected String faxNo;
    @XmlAttribute(name = "street", required = true)
    protected String street;
    @XmlAttribute(name = "email", required = true)
    protected String email;
    @XmlAttribute(name = "mobileNo", required = true)
    protected String mobileNo;
    @XmlAttribute(name = "officeNo", required = true)
    protected String officeNo;
    @XmlAttribute(name = "telephoneNo", required = true)
    protected String telephoneNo;
    @XmlAttribute(name = "building", required = true)
    protected String building;

    /**
     * Gets the value of the areaId property.
     * 
     */
    public long getAreaId() {
        return areaId;
    }

    /**
     * Sets the value of the areaId property.
     * 
     */
    public void setAreaId(long value) {
        this.areaId = value;
    }

    /**
     * Gets the value of the cityId property.
     * 
     */
    public long getCityId() {
        return cityId;
    }

    /**
     * Sets the value of the cityId property.
     * 
     */
    public void setCityId(long value) {
        this.cityId = value;
    }

    /**
     * Gets the value of the emirateId property.
     * 
     */
    public long getEmirateId() {
        return emirateId;
    }

    /**
     * Sets the value of the emirateId property.
     * 
     */
    public void setEmirateId(long value) {
        this.emirateId = value;
    }

    /**
     * Gets the value of the emiratesDepartmentId property.
     * 
     */
    public long getEmiratesDepartmentId() {
        return emiratesDepartmentId;
    }

    /**
     * Sets the value of the emiratesDepartmentId property.
     * 
     */
    public void setEmiratesDepartmentId(long value) {
        this.emiratesDepartmentId = value;
    }

    /**
     * Gets the value of the poBoxEmirateId property.
     * 
     */
    public long getPoBoxEmirateId() {
        return poBoxEmirateId;
    }

    /**
     * Sets the value of the poBoxEmirateId property.
     * 
     */
    public void setPoBoxEmirateId(long value) {
        this.poBoxEmirateId = value;
    }

    /**
     * Gets the value of the poBoxNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPoBoxNo() {
        return poBoxNo;
    }

    /**
     * Sets the value of the poBoxNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPoBoxNo(String value) {
        this.poBoxNo = value;
    }

    /**
     * Gets the value of the flatNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlatNo() {
        return flatNo;
    }

    /**
     * Sets the value of the flatNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlatNo(String value) {
        this.flatNo = value;
    }

    /**
     * Gets the value of the faxNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFaxNo() {
        return faxNo;
    }

    /**
     * Sets the value of the faxNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFaxNo(String value) {
        this.faxNo = value;
    }

    /**
     * Gets the value of the street property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreet() {
        return street;
    }

    /**
     * Sets the value of the street property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreet(String value) {
        this.street = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the mobileNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMobileNo() {
        return mobileNo;
    }

    /**
     * Sets the value of the mobileNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMobileNo(String value) {
        this.mobileNo = value;
    }

    /**
     * Gets the value of the officeNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfficeNo() {
        return officeNo;
    }

    /**
     * Sets the value of the officeNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfficeNo(String value) {
        this.officeNo = value;
    }

    /**
     * Gets the value of the telephoneNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelephoneNo() {
        return telephoneNo;
    }

    /**
     * Sets the value of the telephoneNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelephoneNo(String value) {
        this.telephoneNo = value;
    }

    /**
     * Gets the value of the building property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuilding() {
        return building;
    }

    /**
     * Sets the value of the building property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuilding(String value) {
        this.building = value;
    }

}
