//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.29 at 01:52:13 PM GST 
//


package sdf;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for establishmentRequestBase complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="establishmentRequestBase">
 *   &lt;complexContent>
 *     &lt;extension base="{http://service.api.service.establishment.v2015.emaratech.com/1.0}requestBase">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="applicationPriority" type="{http://www.w3.org/2001/XMLSchema}long" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "establishmentRequestBase")
@XmlSeeAlso({
    ReplaceLostDamageEstabCardAppRequest.class,
    RegisterEstablishmentApplicationRequest.class,
    RenewEstablishmentApplicationRequest.class,
    UpdateEstablishmentApplicationRequest.class,
    CancelEstablishmentApplicationRequest.class
})
public class EstablishmentRequestBase
    extends RequestBase
{

    @XmlAttribute(name = "applicationPriority")
    protected Long applicationPriority;

    /**
     * Gets the value of the applicationPriority property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getApplicationPriority() {
        return applicationPriority;
    }

    /**
     * Sets the value of the applicationPriority property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setApplicationPriority(Long value) {
        this.applicationPriority = value;
    }

}
