//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.29 at 01:52:13 PM GST 
//


package sdf;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for increaseQuotaDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="increaseQuotaDetail">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="VisaType" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="NoOfVisa" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="Reason" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="QuotaExpiryDate" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "increaseQuotaDetail")
public class IncreaseQuotaDetail {

    @XmlAttribute(name = "VisaType", required = true)
    protected long visaType;
    @XmlAttribute(name = "NoOfVisa", required = true)
    protected long noOfVisa;
    @XmlAttribute(name = "Reason", required = true)
    protected long reason;
    @XmlAttribute(name = "QuotaExpiryDate")
    @XmlSchemaType(name = "anySimpleType")
    protected String quotaExpiryDate;

    /**
     * Gets the value of the visaType property.
     * 
     */
    public long getVisaType() {
        return visaType;
    }

    /**
     * Sets the value of the visaType property.
     * 
     */
    public void setVisaType(long value) {
        this.visaType = value;
    }

    /**
     * Gets the value of the noOfVisa property.
     * 
     */
    public long getNoOfVisa() {
        return noOfVisa;
    }

    /**
     * Sets the value of the noOfVisa property.
     * 
     */
    public void setNoOfVisa(long value) {
        this.noOfVisa = value;
    }

    /**
     * Gets the value of the reason property.
     * 
     */
    public long getReason() {
        return reason;
    }

    /**
     * Sets the value of the reason property.
     * 
     */
    public void setReason(long value) {
        this.reason = value;
    }

    /**
     * Gets the value of the quotaExpiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuotaExpiryDate() {
        return quotaExpiryDate;
    }

    /**
     * Sets the value of the quotaExpiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuotaExpiryDate(String value) {
        this.quotaExpiryDate = value;
    }

}
