//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.29 at 01:52:13 PM GST 
//


package sdf;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the sdf package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ReplaceLostDamageEstablishmentCardApplicationResponse_QNAME = new QName("http://service.api.service.establishment.v2015.emaratech.com/1.0", "replaceLostDamageEstablishmentCardApplicationResponse");
    private final static QName _RenewEstablishmentResponse_QNAME = new QName("http://service.api.service.establishment.v2015.emaratech.com/1.0", "renewEstablishmentResponse");
    private final static QName _NewQuotaApplicationResponse_QNAME = new QName("http://service.api.service.establishment.v2015.emaratech.com/1.0", "newQuotaApplicationResponse");
    private final static QName _IncreaseQuotaApplicationResponse_QNAME = new QName("http://service.api.service.establishment.v2015.emaratech.com/1.0", "increaseQuotaApplicationResponse");
    private final static QName _ReduceQuotaApplication_QNAME = new QName("http://service.api.service.establishment.v2015.emaratech.com/1.0", "reduceQuotaApplication");
    private final static QName _RegisterEstablishmentApplicationResponse_QNAME = new QName("http://service.api.service.establishment.v2015.emaratech.com/1.0", "registerEstablishmentApplicationResponse");
    private final static QName _UpdateApplicationDocumentsResponse_QNAME = new QName("http://service.api.service.establishment.v2015.emaratech.com/1.0", "updateApplicationDocumentsResponse");
    private final static QName _QuotaWarrantyPaymentApplicationResponse_QNAME = new QName("http://service.api.service.establishment.v2015.emaratech.com/1.0", "quotaWarrantyPaymentApplicationResponse");
    private final static QName _RenewEstablishmentApplication_QNAME = new QName("http://service.api.service.establishment.v2015.emaratech.com/1.0", "renewEstablishmentApplication");
    private final static QName _ServiceFault_QNAME = new QName("http://service.api.service.establishment.v2015.emaratech.com/1.0", "ServiceFault");
    private final static QName _NewQuotaApplication_QNAME = new QName("http://service.api.service.establishment.v2015.emaratech.com/1.0", "newQuotaApplication");
    private final static QName _UpdateApplicationDocuments_QNAME = new QName("http://service.api.service.establishment.v2015.emaratech.com/1.0", "updateApplicationDocuments");
    private final static QName _IncreaseQuotaApplication_QNAME = new QName("http://service.api.service.establishment.v2015.emaratech.com/1.0", "increaseQuotaApplication");
    private final static QName _CancelEstablishmentApplicationResponse_QNAME = new QName("http://service.api.service.establishment.v2015.emaratech.com/1.0", "cancelEstablishmentApplicationResponse");
    private final static QName _RegisterEstablishmentApplication_QNAME = new QName("http://service.api.service.establishment.v2015.emaratech.com/1.0", "registerEstablishmentApplication");
    private final static QName _RenewEstablishmentApplicationResponse_QNAME = new QName("http://service.api.service.establishment.v2015.emaratech.com/1.0", "renewEstablishmentApplicationResponse");
    private final static QName _ReduceQuotaApplicationResponse_QNAME = new QName("http://service.api.service.establishment.v2015.emaratech.com/1.0", "reduceQuotaApplicationResponse");
    private final static QName _UpdateEstablishmentApplicationResponse_QNAME = new QName("http://service.api.service.establishment.v2015.emaratech.com/1.0", "updateEstablishmentApplicationResponse");
    private final static QName _QuotaWarrantyPaymentApplication_QNAME = new QName("http://service.api.service.establishment.v2015.emaratech.com/1.0", "quotaWarrantyPaymentApplication");
    private final static QName _CancelEstablishmentApplication_QNAME = new QName("http://service.api.service.establishment.v2015.emaratech.com/1.0", "cancelEstablishmentApplication");
    private final static QName _RenewEstablishment_QNAME = new QName("http://service.api.service.establishment.v2015.emaratech.com/1.0", "renewEstablishment");
    private final static QName _UpdateEstablishmentApplication_QNAME = new QName("http://service.api.service.establishment.v2015.emaratech.com/1.0", "updateEstablishmentApplication");
    private final static QName _ReplaceLostDamageEstablishmentCardApplication_QNAME = new QName("http://service.api.service.establishment.v2015.emaratech.com/1.0", "replaceLostDamageEstablishmentCardApplication");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: sdf
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link QuotaWarrantyPaymentApplication }
     * 
     */
    public QuotaWarrantyPaymentApplication createQuotaWarrantyPaymentApplication() {
        return new QuotaWarrantyPaymentApplication();
    }

    /**
     * Create an instance of {@link CancelEstablishmentApplication }
     * 
     */
    public CancelEstablishmentApplication createCancelEstablishmentApplication() {
        return new CancelEstablishmentApplication();
    }

    /**
     * Create an instance of {@link RenewEstablishment }
     * 
     */
    public RenewEstablishment createRenewEstablishment() {
        return new RenewEstablishment();
    }

    /**
     * Create an instance of {@link UpdateEstablishmentApplication }
     * 
     */
    public UpdateEstablishmentApplication createUpdateEstablishmentApplication() {
        return new UpdateEstablishmentApplication();
    }

    /**
     * Create an instance of {@link ReplaceLostDamageEstablishmentCardApplication }
     * 
     */
    public ReplaceLostDamageEstablishmentCardApplication createReplaceLostDamageEstablishmentCardApplication() {
        return new ReplaceLostDamageEstablishmentCardApplication();
    }

    /**
     * Create an instance of {@link IncreaseQuotaApplication }
     * 
     */
    public IncreaseQuotaApplication createIncreaseQuotaApplication() {
        return new IncreaseQuotaApplication();
    }

    /**
     * Create an instance of {@link CancelEstablishmentApplicationResponse }
     * 
     */
    public CancelEstablishmentApplicationResponse createCancelEstablishmentApplicationResponse() {
        return new CancelEstablishmentApplicationResponse();
    }

    /**
     * Create an instance of {@link RegisterEstablishmentApplication }
     * 
     */
    public RegisterEstablishmentApplication createRegisterEstablishmentApplication() {
        return new RegisterEstablishmentApplication();
    }

    /**
     * Create an instance of {@link RenewEstablishmentApplicationResponse }
     * 
     */
    public RenewEstablishmentApplicationResponse createRenewEstablishmentApplicationResponse() {
        return new RenewEstablishmentApplicationResponse();
    }

    /**
     * Create an instance of {@link ReduceQuotaApplicationResponse }
     * 
     */
    public ReduceQuotaApplicationResponse createReduceQuotaApplicationResponse() {
        return new ReduceQuotaApplicationResponse();
    }

    /**
     * Create an instance of {@link UpdateEstablishmentApplicationResponse }
     * 
     */
    public UpdateEstablishmentApplicationResponse createUpdateEstablishmentApplicationResponse() {
        return new UpdateEstablishmentApplicationResponse();
    }

    /**
     * Create an instance of {@link RegisterEstablishmentApplicationResponse }
     * 
     */
    public RegisterEstablishmentApplicationResponse createRegisterEstablishmentApplicationResponse() {
        return new RegisterEstablishmentApplicationResponse();
    }

    /**
     * Create an instance of {@link UpdateApplicationDocumentsResponse }
     * 
     */
    public UpdateApplicationDocumentsResponse createUpdateApplicationDocumentsResponse() {
        return new UpdateApplicationDocumentsResponse();
    }

    /**
     * Create an instance of {@link QuotaWarrantyPaymentApplicationResponse }
     * 
     */
    public QuotaWarrantyPaymentApplicationResponse createQuotaWarrantyPaymentApplicationResponse() {
        return new QuotaWarrantyPaymentApplicationResponse();
    }

    /**
     * Create an instance of {@link RenewEstablishmentApplication }
     * 
     */
    public RenewEstablishmentApplication createRenewEstablishmentApplication() {
        return new RenewEstablishmentApplication();
    }

    /**
     * Create an instance of {@link ApplicationFaultInfo }
     * 
     */
    public ApplicationFaultInfo createApplicationFaultInfo() {
        return new ApplicationFaultInfo();
    }

    /**
     * Create an instance of {@link NewQuotaApplication }
     * 
     */
    public NewQuotaApplication createNewQuotaApplication() {
        return new NewQuotaApplication();
    }

    /**
     * Create an instance of {@link UpdateApplicationDocuments }
     * 
     */
    public UpdateApplicationDocuments createUpdateApplicationDocuments() {
        return new UpdateApplicationDocuments();
    }

    /**
     * Create an instance of {@link ReplaceLostDamageEstablishmentCardApplicationResponse }
     * 
     */
    public ReplaceLostDamageEstablishmentCardApplicationResponse createReplaceLostDamageEstablishmentCardApplicationResponse() {
        return new ReplaceLostDamageEstablishmentCardApplicationResponse();
    }

    /**
     * Create an instance of {@link RenewEstablishmentResponse }
     * 
     */
    public RenewEstablishmentResponse createRenewEstablishmentResponse() {
        return new RenewEstablishmentResponse();
    }

    /**
     * Create an instance of {@link NewQuotaApplicationResponse }
     * 
     */
    public NewQuotaApplicationResponse createNewQuotaApplicationResponse() {
        return new NewQuotaApplicationResponse();
    }

    /**
     * Create an instance of {@link IncreaseQuotaApplicationResponse }
     * 
     */
    public IncreaseQuotaApplicationResponse createIncreaseQuotaApplicationResponse() {
        return new IncreaseQuotaApplicationResponse();
    }

    /**
     * Create an instance of {@link ReduceQuotaApplication }
     * 
     */
    public ReduceQuotaApplication createReduceQuotaApplication() {
        return new ReduceQuotaApplication();
    }

    /**
     * Create an instance of {@link UpdateEstablishmentProfileDetail }
     * 
     */
    public UpdateEstablishmentProfileDetail createUpdateEstablishmentProfileDetail() {
        return new UpdateEstablishmentProfileDetail();
    }

    /**
     * Create an instance of {@link QuotaWarrantyPaymentApplicationRequest }
     * 
     */
    public QuotaWarrantyPaymentApplicationRequest createQuotaWarrantyPaymentApplicationRequest() {
        return new QuotaWarrantyPaymentApplicationRequest();
    }

    /**
     * Create an instance of {@link Channel }
     * 
     */
    public Channel createChannel() {
        return new Channel();
    }

    /**
     * Create an instance of {@link EstablishmentLicenseDetail }
     * 
     */
    public EstablishmentLicenseDetail createEstablishmentLicenseDetail() {
        return new EstablishmentLicenseDetail();
    }

    /**
     * Create an instance of {@link ReplaceLostDamageEstabCardAppRequest }
     * 
     */
    public ReplaceLostDamageEstabCardAppRequest createReplaceLostDamageEstabCardAppRequest() {
        return new ReplaceLostDamageEstabCardAppRequest();
    }

    /**
     * Create an instance of {@link ReduceQuotaDetail }
     * 
     */
    public ReduceQuotaDetail createReduceQuotaDetail() {
        return new ReduceQuotaDetail();
    }

    /**
     * Create an instance of {@link ErrorDetail }
     * 
     */
    public ErrorDetail createErrorDetail() {
        return new ErrorDetail();
    }

    /**
     * Create an instance of {@link UpdateEstablishmentLicenseDetail }
     * 
     */
    public UpdateEstablishmentLicenseDetail createUpdateEstablishmentLicenseDetail() {
        return new UpdateEstablishmentLicenseDetail();
    }

    /**
     * Create an instance of {@link EstablishmentProfileDetail }
     * 
     */
    public EstablishmentProfileDetail createEstablishmentProfileDetail() {
        return new EstablishmentProfileDetail();
    }

    /**
     * Create an instance of {@link UpdateApplicationDocumentRequest }
     * 
     */
    public UpdateApplicationDocumentRequest createUpdateApplicationDocumentRequest() {
        return new UpdateApplicationDocumentRequest();
    }

    /**
     * Create an instance of {@link UpdateEstablishmentMemberDetail }
     * 
     */
    public UpdateEstablishmentMemberDetail createUpdateEstablishmentMemberDetail() {
        return new UpdateEstablishmentMemberDetail();
    }

    /**
     * Create an instance of {@link IncreaseQuotaApplicationRequest }
     * 
     */
    public IncreaseQuotaApplicationRequest createIncreaseQuotaApplicationRequest() {
        return new IncreaseQuotaApplicationRequest();
    }

    /**
     * Create an instance of {@link RegisterEstablishmentApplicationRequest }
     * 
     */
    public RegisterEstablishmentApplicationRequest createRegisterEstablishmentApplicationRequest() {
        return new RegisterEstablishmentApplicationRequest();
    }

    /**
     * Create an instance of {@link RenewEstablishmentApplicationRequest }
     * 
     */
    public RenewEstablishmentApplicationRequest createRenewEstablishmentApplicationRequest() {
        return new RenewEstablishmentApplicationRequest();
    }

    /**
     * Create an instance of {@link EstablishmentApplicationResponse }
     * 
     */
    public EstablishmentApplicationResponse createEstablishmentApplicationResponse() {
        return new EstablishmentApplicationResponse();
    }

    /**
     * Create an instance of {@link ReduceQuotaApplicationRequest }
     * 
     */
    public ReduceQuotaApplicationRequest createReduceQuotaApplicationRequest() {
        return new ReduceQuotaApplicationRequest();
    }

    /**
     * Create an instance of {@link Payment }
     * 
     */
    public Payment createPayment() {
        return new Payment();
    }

    /**
     * Create an instance of {@link IncreaseQuotaDetail }
     * 
     */
    public IncreaseQuotaDetail createIncreaseQuotaDetail() {
        return new IncreaseQuotaDetail();
    }

    /**
     * Create an instance of {@link RemoveMembers }
     * 
     */
    public RemoveMembers createRemoveMembers() {
        return new RemoveMembers();
    }

    /**
     * Create an instance of {@link EstablishmentRequestBase }
     * 
     */
    public EstablishmentRequestBase createEstablishmentRequestBase() {
        return new EstablishmentRequestBase();
    }

    /**
     * Create an instance of {@link EstablishmentAddressDetail }
     * 
     */
    public EstablishmentAddressDetail createEstablishmentAddressDetail() {
        return new EstablishmentAddressDetail();
    }

    /**
     * Create an instance of {@link DocumentType }
     * 
     */
    public DocumentType createDocumentType() {
        return new DocumentType();
    }

    /**
     * Create an instance of {@link RenewEstablishmentApplicationWithDocsRequest }
     * 
     */
    public RenewEstablishmentApplicationWithDocsRequest createRenewEstablishmentApplicationWithDocsRequest() {
        return new RenewEstablishmentApplicationWithDocsRequest();
    }

    /**
     * Create an instance of {@link UpdateEstablishmentApplicationRequest }
     * 
     */
    public UpdateEstablishmentApplicationRequest createUpdateEstablishmentApplicationRequest() {
        return new UpdateEstablishmentApplicationRequest();
    }

    /**
     * Create an instance of {@link PaymentDetail }
     * 
     */
    public PaymentDetail createPaymentDetail() {
        return new PaymentDetail();
    }

    /**
     * Create an instance of {@link CardReprintReason }
     * 
     */
    public CardReprintReason createCardReprintReason() {
        return new CardReprintReason();
    }

    /**
     * Create an instance of {@link EstablishmentMemberDetail }
     * 
     */
    public EstablishmentMemberDetail createEstablishmentMemberDetail() {
        return new EstablishmentMemberDetail();
    }

    /**
     * Create an instance of {@link NewQuotaApplicationRequest }
     * 
     */
    public NewQuotaApplicationRequest createNewQuotaApplicationRequest() {
        return new NewQuotaApplicationRequest();
    }

    /**
     * Create an instance of {@link UpdateEstablishmentAddressDetail }
     * 
     */
    public UpdateEstablishmentAddressDetail createUpdateEstablishmentAddressDetail() {
        return new UpdateEstablishmentAddressDetail();
    }

    /**
     * Create an instance of {@link QuotaDetail }
     * 
     */
    public QuotaDetail createQuotaDetail() {
        return new QuotaDetail();
    }

    /**
     * Create an instance of {@link ApplicationDocument }
     * 
     */
    public ApplicationDocument createApplicationDocument() {
        return new ApplicationDocument();
    }

    /**
     * Create an instance of {@link ApplicationDocuments }
     * 
     */
    public ApplicationDocuments createApplicationDocuments() {
        return new ApplicationDocuments();
    }

    /**
     * Create an instance of {@link CancelEstablishmentApplicationRequest }
     * 
     */
    public CancelEstablishmentApplicationRequest createCancelEstablishmentApplicationRequest() {
        return new CancelEstablishmentApplicationRequest();
    }

    /**
     * Create an instance of {@link RenewEstablishmentProfileDetail }
     * 
     */
    public RenewEstablishmentProfileDetail createRenewEstablishmentProfileDetail() {
        return new RenewEstablishmentProfileDetail();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReplaceLostDamageEstablishmentCardApplicationResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.api.service.establishment.v2015.emaratech.com/1.0", name = "replaceLostDamageEstablishmentCardApplicationResponse")
    public JAXBElement<ReplaceLostDamageEstablishmentCardApplicationResponse> createReplaceLostDamageEstablishmentCardApplicationResponse(ReplaceLostDamageEstablishmentCardApplicationResponse value) {
        return new JAXBElement<ReplaceLostDamageEstablishmentCardApplicationResponse>(_ReplaceLostDamageEstablishmentCardApplicationResponse_QNAME, ReplaceLostDamageEstablishmentCardApplicationResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RenewEstablishmentResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.api.service.establishment.v2015.emaratech.com/1.0", name = "renewEstablishmentResponse")
    public JAXBElement<RenewEstablishmentResponse> createRenewEstablishmentResponse(RenewEstablishmentResponse value) {
        return new JAXBElement<RenewEstablishmentResponse>(_RenewEstablishmentResponse_QNAME, RenewEstablishmentResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NewQuotaApplicationResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.api.service.establishment.v2015.emaratech.com/1.0", name = "newQuotaApplicationResponse")
    public JAXBElement<NewQuotaApplicationResponse> createNewQuotaApplicationResponse(NewQuotaApplicationResponse value) {
        return new JAXBElement<NewQuotaApplicationResponse>(_NewQuotaApplicationResponse_QNAME, NewQuotaApplicationResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IncreaseQuotaApplicationResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.api.service.establishment.v2015.emaratech.com/1.0", name = "increaseQuotaApplicationResponse")
    public JAXBElement<IncreaseQuotaApplicationResponse> createIncreaseQuotaApplicationResponse(IncreaseQuotaApplicationResponse value) {
        return new JAXBElement<IncreaseQuotaApplicationResponse>(_IncreaseQuotaApplicationResponse_QNAME, IncreaseQuotaApplicationResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReduceQuotaApplication }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.api.service.establishment.v2015.emaratech.com/1.0", name = "reduceQuotaApplication")
    public JAXBElement<ReduceQuotaApplication> createReduceQuotaApplication(ReduceQuotaApplication value) {
        return new JAXBElement<ReduceQuotaApplication>(_ReduceQuotaApplication_QNAME, ReduceQuotaApplication.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegisterEstablishmentApplicationResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.api.service.establishment.v2015.emaratech.com/1.0", name = "registerEstablishmentApplicationResponse")
    public JAXBElement<RegisterEstablishmentApplicationResponse> createRegisterEstablishmentApplicationResponse(RegisterEstablishmentApplicationResponse value) {
        return new JAXBElement<RegisterEstablishmentApplicationResponse>(_RegisterEstablishmentApplicationResponse_QNAME, RegisterEstablishmentApplicationResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateApplicationDocumentsResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.api.service.establishment.v2015.emaratech.com/1.0", name = "updateApplicationDocumentsResponse")
    public JAXBElement<UpdateApplicationDocumentsResponse> createUpdateApplicationDocumentsResponse(UpdateApplicationDocumentsResponse value) {
        return new JAXBElement<UpdateApplicationDocumentsResponse>(_UpdateApplicationDocumentsResponse_QNAME, UpdateApplicationDocumentsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QuotaWarrantyPaymentApplicationResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.api.service.establishment.v2015.emaratech.com/1.0", name = "quotaWarrantyPaymentApplicationResponse")
    public JAXBElement<QuotaWarrantyPaymentApplicationResponse> createQuotaWarrantyPaymentApplicationResponse(QuotaWarrantyPaymentApplicationResponse value) {
        return new JAXBElement<QuotaWarrantyPaymentApplicationResponse>(_QuotaWarrantyPaymentApplicationResponse_QNAME, QuotaWarrantyPaymentApplicationResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RenewEstablishmentApplication }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.api.service.establishment.v2015.emaratech.com/1.0", name = "renewEstablishmentApplication")
    public JAXBElement<RenewEstablishmentApplication> createRenewEstablishmentApplication(RenewEstablishmentApplication value) {
        return new JAXBElement<RenewEstablishmentApplication>(_RenewEstablishmentApplication_QNAME, RenewEstablishmentApplication.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ApplicationFaultInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.api.service.establishment.v2015.emaratech.com/1.0", name = "ServiceFault")
    public JAXBElement<ApplicationFaultInfo> createServiceFault(ApplicationFaultInfo value) {
        return new JAXBElement<ApplicationFaultInfo>(_ServiceFault_QNAME, ApplicationFaultInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NewQuotaApplication }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.api.service.establishment.v2015.emaratech.com/1.0", name = "newQuotaApplication")
    public JAXBElement<NewQuotaApplication> createNewQuotaApplication(NewQuotaApplication value) {
        return new JAXBElement<NewQuotaApplication>(_NewQuotaApplication_QNAME, NewQuotaApplication.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateApplicationDocuments }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.api.service.establishment.v2015.emaratech.com/1.0", name = "updateApplicationDocuments")
    public JAXBElement<UpdateApplicationDocuments> createUpdateApplicationDocuments(UpdateApplicationDocuments value) {
        return new JAXBElement<UpdateApplicationDocuments>(_UpdateApplicationDocuments_QNAME, UpdateApplicationDocuments.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IncreaseQuotaApplication }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.api.service.establishment.v2015.emaratech.com/1.0", name = "increaseQuotaApplication")
    public JAXBElement<IncreaseQuotaApplication> createIncreaseQuotaApplication(IncreaseQuotaApplication value) {
        return new JAXBElement<IncreaseQuotaApplication>(_IncreaseQuotaApplication_QNAME, IncreaseQuotaApplication.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CancelEstablishmentApplicationResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.api.service.establishment.v2015.emaratech.com/1.0", name = "cancelEstablishmentApplicationResponse")
    public JAXBElement<CancelEstablishmentApplicationResponse> createCancelEstablishmentApplicationResponse(CancelEstablishmentApplicationResponse value) {
        return new JAXBElement<CancelEstablishmentApplicationResponse>(_CancelEstablishmentApplicationResponse_QNAME, CancelEstablishmentApplicationResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegisterEstablishmentApplication }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.api.service.establishment.v2015.emaratech.com/1.0", name = "registerEstablishmentApplication")
    public JAXBElement<RegisterEstablishmentApplication> createRegisterEstablishmentApplication(RegisterEstablishmentApplication value) {
        return new JAXBElement<RegisterEstablishmentApplication>(_RegisterEstablishmentApplication_QNAME, RegisterEstablishmentApplication.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RenewEstablishmentApplicationResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.api.service.establishment.v2015.emaratech.com/1.0", name = "renewEstablishmentApplicationResponse")
    public JAXBElement<RenewEstablishmentApplicationResponse> createRenewEstablishmentApplicationResponse(RenewEstablishmentApplicationResponse value) {
        return new JAXBElement<RenewEstablishmentApplicationResponse>(_RenewEstablishmentApplicationResponse_QNAME, RenewEstablishmentApplicationResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReduceQuotaApplicationResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.api.service.establishment.v2015.emaratech.com/1.0", name = "reduceQuotaApplicationResponse")
    public JAXBElement<ReduceQuotaApplicationResponse> createReduceQuotaApplicationResponse(ReduceQuotaApplicationResponse value) {
        return new JAXBElement<ReduceQuotaApplicationResponse>(_ReduceQuotaApplicationResponse_QNAME, ReduceQuotaApplicationResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateEstablishmentApplicationResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.api.service.establishment.v2015.emaratech.com/1.0", name = "updateEstablishmentApplicationResponse")
    public JAXBElement<UpdateEstablishmentApplicationResponse> createUpdateEstablishmentApplicationResponse(UpdateEstablishmentApplicationResponse value) {
        return new JAXBElement<UpdateEstablishmentApplicationResponse>(_UpdateEstablishmentApplicationResponse_QNAME, UpdateEstablishmentApplicationResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QuotaWarrantyPaymentApplication }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.api.service.establishment.v2015.emaratech.com/1.0", name = "quotaWarrantyPaymentApplication")
    public JAXBElement<QuotaWarrantyPaymentApplication> createQuotaWarrantyPaymentApplication(QuotaWarrantyPaymentApplication value) {
        return new JAXBElement<QuotaWarrantyPaymentApplication>(_QuotaWarrantyPaymentApplication_QNAME, QuotaWarrantyPaymentApplication.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CancelEstablishmentApplication }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.api.service.establishment.v2015.emaratech.com/1.0", name = "cancelEstablishmentApplication")
    public JAXBElement<CancelEstablishmentApplication> createCancelEstablishmentApplication(CancelEstablishmentApplication value) {
        return new JAXBElement<CancelEstablishmentApplication>(_CancelEstablishmentApplication_QNAME, CancelEstablishmentApplication.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RenewEstablishment }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.api.service.establishment.v2015.emaratech.com/1.0", name = "renewEstablishment")
    public JAXBElement<RenewEstablishment> createRenewEstablishment(RenewEstablishment value) {
        return new JAXBElement<RenewEstablishment>(_RenewEstablishment_QNAME, RenewEstablishment.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateEstablishmentApplication }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.api.service.establishment.v2015.emaratech.com/1.0", name = "updateEstablishmentApplication")
    public JAXBElement<UpdateEstablishmentApplication> createUpdateEstablishmentApplication(UpdateEstablishmentApplication value) {
        return new JAXBElement<UpdateEstablishmentApplication>(_UpdateEstablishmentApplication_QNAME, UpdateEstablishmentApplication.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReplaceLostDamageEstablishmentCardApplication }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.api.service.establishment.v2015.emaratech.com/1.0", name = "replaceLostDamageEstablishmentCardApplication")
    public JAXBElement<ReplaceLostDamageEstablishmentCardApplication> createReplaceLostDamageEstablishmentCardApplication(ReplaceLostDamageEstablishmentCardApplication value) {
        return new JAXBElement<ReplaceLostDamageEstablishmentCardApplication>(_ReplaceLostDamageEstablishmentCardApplication_QNAME, ReplaceLostDamageEstablishmentCardApplication.class, null, value);
    }

}
