//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.29 at 01:52:13 PM GST 
//


package sdf;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Payment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Payment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="feeTypeId" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="PayableAmount" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="PaidAmount" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="Units" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="PaymentExemptionReasonId" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="comment" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Payment")
public class Payment {

    @XmlAttribute(name = "feeTypeId", required = true)
    protected long feeTypeId;
    @XmlAttribute(name = "PayableAmount", required = true)
    protected float payableAmount;
    @XmlAttribute(name = "PaidAmount", required = true)
    protected float paidAmount;
    @XmlAttribute(name = "Units", required = true)
    protected int units;
    @XmlAttribute(name = "PaymentExemptionReasonId")
    protected Long paymentExemptionReasonId;
    @XmlAttribute(name = "comment")
    protected String comment;

    /**
     * Gets the value of the feeTypeId property.
     * 
     */
    public long getFeeTypeId() {
        return feeTypeId;
    }

    /**
     * Sets the value of the feeTypeId property.
     * 
     */
    public void setFeeTypeId(long value) {
        this.feeTypeId = value;
    }

    /**
     * Gets the value of the payableAmount property.
     * 
     */
    public float getPayableAmount() {
        return payableAmount;
    }

    /**
     * Sets the value of the payableAmount property.
     * 
     */
    public void setPayableAmount(float value) {
        this.payableAmount = value;
    }

    /**
     * Gets the value of the paidAmount property.
     * 
     */
    public float getPaidAmount() {
        return paidAmount;
    }

    /**
     * Sets the value of the paidAmount property.
     * 
     */
    public void setPaidAmount(float value) {
        this.paidAmount = value;
    }

    /**
     * Gets the value of the units property.
     * 
     */
    public int getUnits() {
        return units;
    }

    /**
     * Sets the value of the units property.
     * 
     */
    public void setUnits(int value) {
        this.units = value;
    }

    /**
     * Gets the value of the paymentExemptionReasonId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getPaymentExemptionReasonId() {
        return paymentExemptionReasonId;
    }

    /**
     * Sets the value of the paymentExemptionReasonId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setPaymentExemptionReasonId(Long value) {
        this.paymentExemptionReasonId = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

}
