//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.29 at 01:52:13 PM GST 
//


package sdf;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for reduceQuotaApplication complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="reduceQuotaApplication">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="reduceQuotaApplicationRequest" type="{http://service.api.service.establishment.v2015.emaratech.com/1.0}reduceQuotaApplicationRequest" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "reduceQuotaApplication", propOrder = {
    "reduceQuotaApplicationRequest"
})
public class ReduceQuotaApplication {

    protected ReduceQuotaApplicationRequest reduceQuotaApplicationRequest;

    /**
     * Gets the value of the reduceQuotaApplicationRequest property.
     * 
     * @return
     *     possible object is
     *     {@link ReduceQuotaApplicationRequest }
     *     
     */
    public ReduceQuotaApplicationRequest getReduceQuotaApplicationRequest() {
        return reduceQuotaApplicationRequest;
    }

    /**
     * Sets the value of the reduceQuotaApplicationRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReduceQuotaApplicationRequest }
     *     
     */
    public void setReduceQuotaApplicationRequest(ReduceQuotaApplicationRequest value) {
        this.reduceQuotaApplicationRequest = value;
    }

}
