//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.29 at 01:52:13 PM GST 
//


package sdf;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for registerEstablishmentApplicationRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="registerEstablishmentApplicationRequest">
 *   &lt;complexContent>
 *     &lt;extension base="{http://service.api.service.establishment.v2015.emaratech.com/1.0}establishmentRequestBase">
 *       &lt;sequence>
 *         &lt;element name="EstablishmentProfileDetail" type="{http://service.api.service.establishment.v2015.emaratech.com/1.0}EstablishmentProfileDetail"/>
 *         &lt;element name="EstablishmentLicenseDetail" type="{http://service.api.service.establishment.v2015.emaratech.com/1.0}EstablishmentLicenseDetail"/>
 *         &lt;element name="EstablishmentMemberDetail" type="{http://service.api.service.establishment.v2015.emaratech.com/1.0}EstablishmentMemberDetail" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PaymentDetail" type="{http://service.api.service.establishment.v2015.emaratech.com/1.0}PaymentDetail"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ApplicationNo" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "registerEstablishmentApplicationRequest", propOrder = {
    "establishmentProfileDetail",
    "establishmentLicenseDetail",
    "establishmentMemberDetail",
    "paymentDetail"
})
public class RegisterEstablishmentApplicationRequest
    extends EstablishmentRequestBase
{

    @XmlElement(name = "EstablishmentProfileDetail", required = true)
    protected EstablishmentProfileDetail establishmentProfileDetail;
    @XmlElement(name = "EstablishmentLicenseDetail", required = true)
    protected EstablishmentLicenseDetail establishmentLicenseDetail;
    @XmlElement(name = "EstablishmentMemberDetail")
    protected List<EstablishmentMemberDetail> establishmentMemberDetail;
    @XmlElement(name = "PaymentDetail", required = true)
    protected PaymentDetail paymentDetail;
    @XmlAttribute(name = "ApplicationNo", required = true)
    protected long applicationNo;

    /**
     * Gets the value of the establishmentProfileDetail property.
     * 
     * @return
     *     possible object is
     *     {@link EstablishmentProfileDetail }
     *     
     */
    public EstablishmentProfileDetail getEstablishmentProfileDetail() {
        return establishmentProfileDetail;
    }

    /**
     * Sets the value of the establishmentProfileDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link EstablishmentProfileDetail }
     *     
     */
    public void setEstablishmentProfileDetail(EstablishmentProfileDetail value) {
        this.establishmentProfileDetail = value;
    }

    /**
     * Gets the value of the establishmentLicenseDetail property.
     * 
     * @return
     *     possible object is
     *     {@link EstablishmentLicenseDetail }
     *     
     */
    public EstablishmentLicenseDetail getEstablishmentLicenseDetail() {
        return establishmentLicenseDetail;
    }

    /**
     * Sets the value of the establishmentLicenseDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link EstablishmentLicenseDetail }
     *     
     */
    public void setEstablishmentLicenseDetail(EstablishmentLicenseDetail value) {
        this.establishmentLicenseDetail = value;
    }

    /**
     * Gets the value of the establishmentMemberDetail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the establishmentMemberDetail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEstablishmentMemberDetail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EstablishmentMemberDetail }
     * 
     * 
     */
    public List<EstablishmentMemberDetail> getEstablishmentMemberDetail() {
        if (establishmentMemberDetail == null) {
            establishmentMemberDetail = new ArrayList<EstablishmentMemberDetail>();
        }
        return this.establishmentMemberDetail;
    }

    /**
     * Gets the value of the paymentDetail property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentDetail }
     *     
     */
    public PaymentDetail getPaymentDetail() {
        return paymentDetail;
    }

    /**
     * Sets the value of the paymentDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentDetail }
     *     
     */
    public void setPaymentDetail(PaymentDetail value) {
        this.paymentDetail = value;
    }

    /**
     * Gets the value of the applicationNo property.
     * 
     */
    public long getApplicationNo() {
        return applicationNo;
    }

    /**
     * Sets the value of the applicationNo property.
     * 
     */
    public void setApplicationNo(long value) {
        this.applicationNo = value;
    }

}
