//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.29 at 01:52:13 PM GST 
//


package sdf;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RemoveMembers complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RemoveMembers">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="UDB" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="establishmentCode" type="{http://www.w3.org/2001/XMLSchema}long" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RemoveMembers")
public class RemoveMembers {

    @XmlAttribute(name = "UDB")
    protected Long udb;
    @XmlAttribute(name = "establishmentCode")
    protected Long establishmentCode;

    /**
     * Gets the value of the udb property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getUDB() {
        return udb;
    }

    /**
     * Sets the value of the udb property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setUDB(Long value) {
        this.udb = value;
    }

    /**
     * Gets the value of the establishmentCode property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getEstablishmentCode() {
        return establishmentCode;
    }

    /**
     * Sets the value of the establishmentCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setEstablishmentCode(Long value) {
        this.establishmentCode = value;
    }

}
