//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.29 at 01:52:13 PM GST 
//


package sdf;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for renewEstablishmentApplicationWithDocsRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="renewEstablishmentApplicationWithDocsRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="applicationDocuments" type="{http://service.api.service.establishment.v2015.emaratech.com/1.0}applicationDocuments" minOccurs="0"/>
 *         &lt;element name="renewEstablishmentApplicationRequest" type="{http://service.api.service.establishment.v2015.emaratech.com/1.0}renewEstablishmentApplicationRequest"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "renewEstablishmentApplicationWithDocsRequest", propOrder = {
    "applicationDocuments",
    "renewEstablishmentApplicationRequest"
})
public class RenewEstablishmentApplicationWithDocsRequest {

    protected ApplicationDocuments applicationDocuments;
    @XmlElement(required = true)
    protected RenewEstablishmentApplicationRequest renewEstablishmentApplicationRequest;

    /**
     * Gets the value of the applicationDocuments property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationDocuments }
     *     
     */
    public ApplicationDocuments getApplicationDocuments() {
        return applicationDocuments;
    }

    /**
     * Sets the value of the applicationDocuments property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationDocuments }
     *     
     */
    public void setApplicationDocuments(ApplicationDocuments value) {
        this.applicationDocuments = value;
    }

    /**
     * Gets the value of the renewEstablishmentApplicationRequest property.
     * 
     * @return
     *     possible object is
     *     {@link RenewEstablishmentApplicationRequest }
     *     
     */
    public RenewEstablishmentApplicationRequest getRenewEstablishmentApplicationRequest() {
        return renewEstablishmentApplicationRequest;
    }

    /**
     * Sets the value of the renewEstablishmentApplicationRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link RenewEstablishmentApplicationRequest }
     *     
     */
    public void setRenewEstablishmentApplicationRequest(RenewEstablishmentApplicationRequest value) {
        this.renewEstablishmentApplicationRequest = value;
    }

}
