//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.29 at 01:52:13 PM GST 
//


package sdf;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RenewEstablishmentProfileDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RenewEstablishmentProfileDetail">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="updateEstablishmentAddressDetail" type="{http://service.api.service.establishment.v2015.emaratech.com/1.0}UpdateEstablishmentAddressDetail" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="nameEnglish" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="nameArabic" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="registrationExpiryYears" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="beneficiary" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RenewEstablishmentProfileDetail", propOrder = {
    "updateEstablishmentAddressDetail"
})
public class RenewEstablishmentProfileDetail {

    protected UpdateEstablishmentAddressDetail updateEstablishmentAddressDetail;
    @XmlAttribute(name = "nameEnglish")
    protected String nameEnglish;
    @XmlAttribute(name = "nameArabic")
    protected String nameArabic;
    @XmlAttribute(name = "registrationExpiryYears", required = true)
    protected long registrationExpiryYears;
    @XmlAttribute(name = "beneficiary", required = true)
    protected boolean beneficiary;

    /**
     * Gets the value of the updateEstablishmentAddressDetail property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateEstablishmentAddressDetail }
     *     
     */
    public UpdateEstablishmentAddressDetail getUpdateEstablishmentAddressDetail() {
        return updateEstablishmentAddressDetail;
    }

    /**
     * Sets the value of the updateEstablishmentAddressDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateEstablishmentAddressDetail }
     *     
     */
    public void setUpdateEstablishmentAddressDetail(UpdateEstablishmentAddressDetail value) {
        this.updateEstablishmentAddressDetail = value;
    }

    /**
     * Gets the value of the nameEnglish property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameEnglish() {
        return nameEnglish;
    }

    /**
     * Sets the value of the nameEnglish property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameEnglish(String value) {
        this.nameEnglish = value;
    }

    /**
     * Gets the value of the nameArabic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameArabic() {
        return nameArabic;
    }

    /**
     * Sets the value of the nameArabic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameArabic(String value) {
        this.nameArabic = value;
    }

    /**
     * Gets the value of the registrationExpiryYears property.
     * 
     */
    public long getRegistrationExpiryYears() {
        return registrationExpiryYears;
    }

    /**
     * Sets the value of the registrationExpiryYears property.
     * 
     */
    public void setRegistrationExpiryYears(long value) {
        this.registrationExpiryYears = value;
    }

    /**
     * Gets the value of the beneficiary property.
     * 
     */
    public boolean isBeneficiary() {
        return beneficiary;
    }

    /**
     * Sets the value of the beneficiary property.
     * 
     */
    public void setBeneficiary(boolean value) {
        this.beneficiary = value;
    }

}
