//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.29 at 01:52:13 PM GST 
//


package sdf;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for renewEstablishmentApplicationRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="renewEstablishmentApplicationRequest">
 *   &lt;complexContent>
 *     &lt;extension base="{http://service.api.service.establishment.v2015.emaratech.com/1.0}establishmentRequestBase">
 *       &lt;sequence>
 *         &lt;element name="RenewEstablishmentProfileDetail" type="{http://service.api.service.establishment.v2015.emaratech.com/1.0}RenewEstablishmentProfileDetail"/>
 *         &lt;element name="UpdateEstablishmentLicenseDetail" type="{http://service.api.service.establishment.v2015.emaratech.com/1.0}UpdateEstablishmentLicenseDetail"/>
 *         &lt;element name="NewEstablishmentMemberDetail" type="{http://service.api.service.establishment.v2015.emaratech.com/1.0}EstablishmentMemberDetail" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="UpdateEstablishmentMemberDetail" type="{http://service.api.service.establishment.v2015.emaratech.com/1.0}UpdateEstablishmentMemberDetail" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="RemoveEstablishmentMember" type="{http://service.api.service.establishment.v2015.emaratech.com/1.0}RemoveMembers" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PaymentDetail" type="{http://service.api.service.establishment.v2015.emaratech.com/1.0}PaymentDetail"/>
 *       &lt;/sequence>
 *       &lt;attribute name="establishmentCode" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="ApplicationNo" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="isAutoApproval" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "renewEstablishmentApplicationRequest", propOrder = {
    "renewEstablishmentProfileDetail",
    "updateEstablishmentLicenseDetail",
    "newEstablishmentMemberDetail",
    "updateEstablishmentMemberDetail",
    "removeEstablishmentMember",
    "paymentDetail"
})
public class RenewEstablishmentApplicationRequest
    extends EstablishmentRequestBase
{

    @XmlElement(name = "RenewEstablishmentProfileDetail", required = true)
    protected RenewEstablishmentProfileDetail renewEstablishmentProfileDetail;
    @XmlElement(name = "UpdateEstablishmentLicenseDetail", required = true)
    protected UpdateEstablishmentLicenseDetail updateEstablishmentLicenseDetail;
    @XmlElement(name = "NewEstablishmentMemberDetail")
    protected List<EstablishmentMemberDetail> newEstablishmentMemberDetail;
    @XmlElement(name = "UpdateEstablishmentMemberDetail")
    protected List<UpdateEstablishmentMemberDetail> updateEstablishmentMemberDetail;
    @XmlElement(name = "RemoveEstablishmentMember")
    protected List<RemoveMembers> removeEstablishmentMember;
    @XmlElement(name = "PaymentDetail", required = true)
    protected PaymentDetail paymentDetail;
    @XmlAttribute(name = "establishmentCode", required = true)
    protected long establishmentCode;
    @XmlAttribute(name = "ApplicationNo", required = true)
    protected long applicationNo;
    @XmlAttribute(name = "isAutoApproval")
    protected Boolean isAutoApproval;

    /**
     * Gets the value of the renewEstablishmentProfileDetail property.
     * 
     * @return
     *     possible object is
     *     {@link RenewEstablishmentProfileDetail }
     *     
     */
    public RenewEstablishmentProfileDetail getRenewEstablishmentProfileDetail() {
        return renewEstablishmentProfileDetail;
    }

    /**
     * Sets the value of the renewEstablishmentProfileDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link RenewEstablishmentProfileDetail }
     *     
     */
    public void setRenewEstablishmentProfileDetail(RenewEstablishmentProfileDetail value) {
        this.renewEstablishmentProfileDetail = value;
    }

    /**
     * Gets the value of the updateEstablishmentLicenseDetail property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateEstablishmentLicenseDetail }
     *     
     */
    public UpdateEstablishmentLicenseDetail getUpdateEstablishmentLicenseDetail() {
        return updateEstablishmentLicenseDetail;
    }

    /**
     * Sets the value of the updateEstablishmentLicenseDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateEstablishmentLicenseDetail }
     *     
     */
    public void setUpdateEstablishmentLicenseDetail(UpdateEstablishmentLicenseDetail value) {
        this.updateEstablishmentLicenseDetail = value;
    }

    /**
     * Gets the value of the newEstablishmentMemberDetail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the newEstablishmentMemberDetail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNewEstablishmentMemberDetail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EstablishmentMemberDetail }
     * 
     * 
     */
    public List<EstablishmentMemberDetail> getNewEstablishmentMemberDetail() {
        if (newEstablishmentMemberDetail == null) {
            newEstablishmentMemberDetail = new ArrayList<EstablishmentMemberDetail>();
        }
        return this.newEstablishmentMemberDetail;
    }

    /**
     * Gets the value of the updateEstablishmentMemberDetail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the updateEstablishmentMemberDetail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUpdateEstablishmentMemberDetail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UpdateEstablishmentMemberDetail }
     * 
     * 
     */
    public List<UpdateEstablishmentMemberDetail> getUpdateEstablishmentMemberDetail() {
        if (updateEstablishmentMemberDetail == null) {
            updateEstablishmentMemberDetail = new ArrayList<UpdateEstablishmentMemberDetail>();
        }
        return this.updateEstablishmentMemberDetail;
    }

    /**
     * Gets the value of the removeEstablishmentMember property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the removeEstablishmentMember property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRemoveEstablishmentMember().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RemoveMembers }
     * 
     * 
     */
    public List<RemoveMembers> getRemoveEstablishmentMember() {
        if (removeEstablishmentMember == null) {
            removeEstablishmentMember = new ArrayList<RemoveMembers>();
        }
        return this.removeEstablishmentMember;
    }

    /**
     * Gets the value of the paymentDetail property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentDetail }
     *     
     */
    public PaymentDetail getPaymentDetail() {
        return paymentDetail;
    }

    /**
     * Sets the value of the paymentDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentDetail }
     *     
     */
    public void setPaymentDetail(PaymentDetail value) {
        this.paymentDetail = value;
    }

    /**
     * Gets the value of the establishmentCode property.
     * 
     */
    public long getEstablishmentCode() {
        return establishmentCode;
    }

    /**
     * Sets the value of the establishmentCode property.
     * 
     */
    public void setEstablishmentCode(long value) {
        this.establishmentCode = value;
    }

    /**
     * Gets the value of the applicationNo property.
     * 
     */
    public long getApplicationNo() {
        return applicationNo;
    }

    /**
     * Sets the value of the applicationNo property.
     * 
     */
    public void setApplicationNo(long value) {
        this.applicationNo = value;
    }

    /**
     * Gets the value of the isAutoApproval property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsAutoApproval() {
        return isAutoApproval;
    }

    /**
     * Sets the value of the isAutoApproval property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsAutoApproval(Boolean value) {
        this.isAutoApproval = value;
    }

}
