//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.29 at 01:52:13 PM GST 
//


package sdf;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for replaceLostDamageEstabCardAppRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="replaceLostDamageEstabCardAppRequest">
 *   &lt;complexContent>
 *     &lt;extension base="{http://service.api.service.establishment.v2015.emaratech.com/1.0}establishmentRequestBase">
 *       &lt;sequence>
 *         &lt;element name="CardNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Reason" type="{http://service.api.service.establishment.v2015.emaratech.com/1.0}cardReprintReason"/>
 *         &lt;element name="PaymentDetail" type="{http://service.api.service.establishment.v2015.emaratech.com/1.0}PaymentDetail"/>
 *       &lt;/sequence>
 *       &lt;attribute name="EstablishmentCode" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="ApplicationNo" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "replaceLostDamageEstabCardAppRequest", propOrder = {
    "cardNo",
    "reason",
    "paymentDetail"
})
public class ReplaceLostDamageEstabCardAppRequest
    extends EstablishmentRequestBase
{

    @XmlElement(name = "CardNo", required = true)
    protected String cardNo;
    @XmlElement(name = "Reason", required = true)
    protected CardReprintReason reason;
    @XmlElement(name = "PaymentDetail", required = true)
    protected PaymentDetail paymentDetail;
    @XmlAttribute(name = "EstablishmentCode", required = true)
    protected long establishmentCode;
    @XmlAttribute(name = "ApplicationNo", required = true)
    protected long applicationNo;

    /**
     * Gets the value of the cardNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * Sets the value of the cardNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardNo(String value) {
        this.cardNo = value;
    }

    /**
     * Gets the value of the reason property.
     * 
     * @return
     *     possible object is
     *     {@link CardReprintReason }
     *     
     */
    public CardReprintReason getReason() {
        return reason;
    }

    /**
     * Sets the value of the reason property.
     * 
     * @param value
     *     allowed object is
     *     {@link CardReprintReason }
     *     
     */
    public void setReason(CardReprintReason value) {
        this.reason = value;
    }

    /**
     * Gets the value of the paymentDetail property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentDetail }
     *     
     */
    public PaymentDetail getPaymentDetail() {
        return paymentDetail;
    }

    /**
     * Sets the value of the paymentDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentDetail }
     *     
     */
    public void setPaymentDetail(PaymentDetail value) {
        this.paymentDetail = value;
    }

    /**
     * Gets the value of the establishmentCode property.
     * 
     */
    public long getEstablishmentCode() {
        return establishmentCode;
    }

    /**
     * Sets the value of the establishmentCode property.
     * 
     */
    public void setEstablishmentCode(long value) {
        this.establishmentCode = value;
    }

    /**
     * Gets the value of the applicationNo property.
     * 
     */
    public long getApplicationNo() {
        return applicationNo;
    }

    /**
     * Sets the value of the applicationNo property.
     * 
     */
    public void setApplicationNo(long value) {
        this.applicationNo = value;
    }

}
