//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.29 at 01:52:13 PM GST 
//


package sdf;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for requestBase complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="requestBase">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="operatedBy" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="operationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="source" type="{http://service.api.service.establishment.v2015.emaratech.com/1.0}channel"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "requestBase", propOrder = {
    "operatedBy",
    "operationDate",
    "source"
})
@XmlSeeAlso({
    QuotaWarrantyPaymentApplicationRequest.class,
    UpdateApplicationDocumentRequest.class,
    IncreaseQuotaApplicationRequest.class,
    ReduceQuotaApplicationRequest.class,
    NewQuotaApplicationRequest.class,
    EstablishmentRequestBase.class
})
public abstract class RequestBase {

    protected long operatedBy;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar operationDate;
    @XmlElement(required = true)
    protected Channel source;

    /**
     * Gets the value of the operatedBy property.
     * 
     */
    public long getOperatedBy() {
        return operatedBy;
    }

    /**
     * Sets the value of the operatedBy property.
     * 
     */
    public void setOperatedBy(long value) {
        this.operatedBy = value;
    }

    /**
     * Gets the value of the operationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOperationDate() {
        return operationDate;
    }

    /**
     * Sets the value of the operationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOperationDate(XMLGregorianCalendar value) {
        this.operationDate = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link Channel }
     *     
     */
    public Channel getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link Channel }
     *     
     */
    public void setSource(Channel value) {
        this.source = value;
    }

}
