//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.29 at 01:52:13 PM GST 
//


package sdf;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for updateEstablishmentApplicationRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="updateEstablishmentApplicationRequest">
 *   &lt;complexContent>
 *     &lt;extension base="{http://service.api.service.establishment.v2015.emaratech.com/1.0}establishmentRequestBase">
 *       &lt;sequence>
 *         &lt;element name="UpdateEstablishmentProfileDetail" type="{http://service.api.service.establishment.v2015.emaratech.com/1.0}UpdateEstablishmentProfileDetail" minOccurs="0"/>
 *         &lt;element name="UpdateEstablishmentLicenseDetail" type="{http://service.api.service.establishment.v2015.emaratech.com/1.0}UpdateEstablishmentLicenseDetail" minOccurs="0"/>
 *         &lt;element name="NewEstablishmentMemberDetail" type="{http://service.api.service.establishment.v2015.emaratech.com/1.0}EstablishmentMemberDetail" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PaymentDetail" type="{http://service.api.service.establishment.v2015.emaratech.com/1.0}PaymentDetail" minOccurs="0"/>
 *         &lt;element name="RemoveEstablishmentMembers" type="{http://service.api.service.establishment.v2015.emaratech.com/1.0}RemoveMembers" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="RemoveQuotaVisaTypeId" type="{http://www.w3.org/2001/XMLSchema}long" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="UpdateEstablishmentMemberDetails" type="{http://service.api.service.establishment.v2015.emaratech.com/1.0}UpdateEstablishmentMemberDetail" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ApplicationNo" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="establishmentCode" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "updateEstablishmentApplicationRequest", propOrder = {
    "updateEstablishmentProfileDetail",
    "updateEstablishmentLicenseDetail",
    "newEstablishmentMemberDetail",
    "paymentDetail",
    "removeEstablishmentMembers",
    "removeQuotaVisaTypeId",
    "updateEstablishmentMemberDetails"
})
public class UpdateEstablishmentApplicationRequest
    extends EstablishmentRequestBase
{

    @XmlElement(name = "UpdateEstablishmentProfileDetail")
    protected UpdateEstablishmentProfileDetail updateEstablishmentProfileDetail;
    @XmlElement(name = "UpdateEstablishmentLicenseDetail")
    protected UpdateEstablishmentLicenseDetail updateEstablishmentLicenseDetail;
    @XmlElement(name = "NewEstablishmentMemberDetail")
    protected List<EstablishmentMemberDetail> newEstablishmentMemberDetail;
    @XmlElement(name = "PaymentDetail")
    protected PaymentDetail paymentDetail;
    @XmlElement(name = "RemoveEstablishmentMembers")
    protected List<RemoveMembers> removeEstablishmentMembers;
    @XmlElement(name = "RemoveQuotaVisaTypeId", type = Long.class)
    protected List<Long> removeQuotaVisaTypeId;
    @XmlElement(name = "UpdateEstablishmentMemberDetails")
    protected List<UpdateEstablishmentMemberDetail> updateEstablishmentMemberDetails;
    @XmlAttribute(name = "ApplicationNo", required = true)
    protected long applicationNo;
    @XmlAttribute(name = "establishmentCode", required = true)
    protected long establishmentCode;

    /**
     * Gets the value of the updateEstablishmentProfileDetail property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateEstablishmentProfileDetail }
     *     
     */
    public UpdateEstablishmentProfileDetail getUpdateEstablishmentProfileDetail() {
        return updateEstablishmentProfileDetail;
    }

    /**
     * Sets the value of the updateEstablishmentProfileDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateEstablishmentProfileDetail }
     *     
     */
    public void setUpdateEstablishmentProfileDetail(UpdateEstablishmentProfileDetail value) {
        this.updateEstablishmentProfileDetail = value;
    }

    /**
     * Gets the value of the updateEstablishmentLicenseDetail property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateEstablishmentLicenseDetail }
     *     
     */
    public UpdateEstablishmentLicenseDetail getUpdateEstablishmentLicenseDetail() {
        return updateEstablishmentLicenseDetail;
    }

    /**
     * Sets the value of the updateEstablishmentLicenseDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateEstablishmentLicenseDetail }
     *     
     */
    public void setUpdateEstablishmentLicenseDetail(UpdateEstablishmentLicenseDetail value) {
        this.updateEstablishmentLicenseDetail = value;
    }

    /**
     * Gets the value of the newEstablishmentMemberDetail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the newEstablishmentMemberDetail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNewEstablishmentMemberDetail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EstablishmentMemberDetail }
     * 
     * 
     */
    public List<EstablishmentMemberDetail> getNewEstablishmentMemberDetail() {
        if (newEstablishmentMemberDetail == null) {
            newEstablishmentMemberDetail = new ArrayList<EstablishmentMemberDetail>();
        }
        return this.newEstablishmentMemberDetail;
    }

    /**
     * Gets the value of the paymentDetail property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentDetail }
     *     
     */
    public PaymentDetail getPaymentDetail() {
        return paymentDetail;
    }

    /**
     * Sets the value of the paymentDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentDetail }
     *     
     */
    public void setPaymentDetail(PaymentDetail value) {
        this.paymentDetail = value;
    }

    /**
     * Gets the value of the removeEstablishmentMembers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the removeEstablishmentMembers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRemoveEstablishmentMembers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RemoveMembers }
     * 
     * 
     */
    public List<RemoveMembers> getRemoveEstablishmentMembers() {
        if (removeEstablishmentMembers == null) {
            removeEstablishmentMembers = new ArrayList<RemoveMembers>();
        }
        return this.removeEstablishmentMembers;
    }

    /**
     * Gets the value of the removeQuotaVisaTypeId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the removeQuotaVisaTypeId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRemoveQuotaVisaTypeId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Long }
     * 
     * 
     */
    public List<Long> getRemoveQuotaVisaTypeId() {
        if (removeQuotaVisaTypeId == null) {
            removeQuotaVisaTypeId = new ArrayList<Long>();
        }
        return this.removeQuotaVisaTypeId;
    }

    /**
     * Gets the value of the updateEstablishmentMemberDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the updateEstablishmentMemberDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUpdateEstablishmentMemberDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UpdateEstablishmentMemberDetail }
     * 
     * 
     */
    public List<UpdateEstablishmentMemberDetail> getUpdateEstablishmentMemberDetails() {
        if (updateEstablishmentMemberDetails == null) {
            updateEstablishmentMemberDetails = new ArrayList<UpdateEstablishmentMemberDetail>();
        }
        return this.updateEstablishmentMemberDetails;
    }

    /**
     * Gets the value of the applicationNo property.
     * 
     */
    public long getApplicationNo() {
        return applicationNo;
    }

    /**
     * Sets the value of the applicationNo property.
     * 
     */
    public void setApplicationNo(long value) {
        this.applicationNo = value;
    }

    /**
     * Gets the value of the establishmentCode property.
     * 
     */
    public long getEstablishmentCode() {
        return establishmentCode;
    }

    /**
     * Sets the value of the establishmentCode property.
     * 
     */
    public void setEstablishmentCode(long value) {
        this.establishmentCode = value;
    }

}
