//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.29 at 01:52:13 PM GST 
//


package sdf;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for updateApplicationDocumentRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="updateApplicationDocumentRequest">
 *   &lt;complexContent>
 *     &lt;extension base="{http://service.api.service.establishment.v2015.emaratech.com/1.0}requestBase">
 *       &lt;sequence>
 *         &lt;element name="applicationDocuments" type="{http://service.api.service.establishment.v2015.emaratech.com/1.0}applicationDocuments"/>
 *         &lt;element name="correlationID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="applicationNo" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "updateApplicationDocumentRequest", propOrder = {
    "applicationDocuments",
    "correlationID"
})
public class UpdateApplicationDocumentRequest
    extends RequestBase
{

    @XmlElement(required = true)
    protected ApplicationDocuments applicationDocuments;
    protected String correlationID;
    @XmlAttribute(name = "applicationNo", required = true)
    protected long applicationNo;

    /**
     * Gets the value of the applicationDocuments property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationDocuments }
     *     
     */
    public ApplicationDocuments getApplicationDocuments() {
        return applicationDocuments;
    }

    /**
     * Sets the value of the applicationDocuments property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationDocuments }
     *     
     */
    public void setApplicationDocuments(ApplicationDocuments value) {
        this.applicationDocuments = value;
    }

    /**
     * Gets the value of the correlationID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorrelationID() {
        return correlationID;
    }

    /**
     * Sets the value of the correlationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorrelationID(String value) {
        this.correlationID = value;
    }

    /**
     * Gets the value of the applicationNo property.
     * 
     */
    public long getApplicationNo() {
        return applicationNo;
    }

    /**
     * Sets the value of the applicationNo property.
     * 
     */
    public void setApplicationNo(long value) {
        this.applicationNo = value;
    }

}
