//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.29 at 01:52:13 PM GST 
//


package sdf;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UpdateEstablishmentMemberDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UpdateEstablishmentMemberDetail">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="UDB" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="signatory" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="UaeId" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="memberTypeId" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UpdateEstablishmentMemberDetail")
public class UpdateEstablishmentMemberDetail {

    @XmlAttribute(name = "UDB", required = true)
    protected long udb;
    @XmlAttribute(name = "signatory", required = true)
    protected boolean signatory;
    @XmlAttribute(name = "UaeId")
    protected Long uaeId;
    @XmlAttribute(name = "memberTypeId", required = true)
    protected long memberTypeId;

    /**
     * Gets the value of the udb property.
     * 
     */
    public long getUDB() {
        return udb;
    }

    /**
     * Sets the value of the udb property.
     * 
     */
    public void setUDB(long value) {
        this.udb = value;
    }

    /**
     * Gets the value of the signatory property.
     * 
     */
    public boolean isSignatory() {
        return signatory;
    }

    /**
     * Sets the value of the signatory property.
     * 
     */
    public void setSignatory(boolean value) {
        this.signatory = value;
    }

    /**
     * Gets the value of the uaeId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getUaeId() {
        return uaeId;
    }

    /**
     * Sets the value of the uaeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setUaeId(Long value) {
        this.uaeId = value;
    }

    /**
     * Gets the value of the memberTypeId property.
     * 
     */
    public long getMemberTypeId() {
        return memberTypeId;
    }

    /**
     * Sets the value of the memberTypeId property.
     * 
     */
    public void setMemberTypeId(long value) {
        this.memberTypeId = value;
    }

}
