//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.29 at 01:52:13 PM GST 
//


package sdf;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for UpdateEstablishmentLicenseDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UpdateEstablishmentLicenseDetail">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="licenseActivity" type="{http://www.w3.org/2001/XMLSchema}long" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="licenseTypeId" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="licenseAuthorityId" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="licenseNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="licenseIssueDate" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="licenseExpiryDate" type="{http://www.w3.org/2001/XMLSchema}date" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UpdateEstablishmentLicenseDetail", propOrder = {
    "licenseActivity"
})
public class UpdateEstablishmentLicenseDetail {

    @XmlElement(type = Long.class)
    protected List<Long> licenseActivity;
    @XmlAttribute(name = "licenseTypeId", required = true)
    protected long licenseTypeId;
    @XmlAttribute(name = "licenseAuthorityId")
    protected Long licenseAuthorityId;
    @XmlAttribute(name = "licenseNumber", required = true)
    protected String licenseNumber;
    @XmlAttribute(name = "licenseIssueDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar licenseIssueDate;
    @XmlAttribute(name = "licenseExpiryDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar licenseExpiryDate;

    /**
     * Gets the value of the licenseActivity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the licenseActivity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLicenseActivity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Long }
     * 
     * 
     */
    public List<Long> getLicenseActivity() {
        if (licenseActivity == null) {
            licenseActivity = new ArrayList<Long>();
        }
        return this.licenseActivity;
    }

    /**
     * Gets the value of the licenseTypeId property.
     * 
     */
    public long getLicenseTypeId() {
        return licenseTypeId;
    }

    /**
     * Sets the value of the licenseTypeId property.
     * 
     */
    public void setLicenseTypeId(long value) {
        this.licenseTypeId = value;
    }

    /**
     * Gets the value of the licenseAuthorityId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getLicenseAuthorityId() {
        return licenseAuthorityId;
    }

    /**
     * Sets the value of the licenseAuthorityId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setLicenseAuthorityId(Long value) {
        this.licenseAuthorityId = value;
    }

    /**
     * Gets the value of the licenseNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLicenseNumber() {
        return licenseNumber;
    }

    /**
     * Sets the value of the licenseNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLicenseNumber(String value) {
        this.licenseNumber = value;
    }

    /**
     * Gets the value of the licenseIssueDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLicenseIssueDate() {
        return licenseIssueDate;
    }

    /**
     * Sets the value of the licenseIssueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLicenseIssueDate(XMLGregorianCalendar value) {
        this.licenseIssueDate = value;
    }

    /**
     * Gets the value of the licenseExpiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLicenseExpiryDate() {
        return licenseExpiryDate;
    }

    /**
     * Sets the value of the licenseExpiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLicenseExpiryDate(XMLGregorianCalendar value) {
        this.licenseExpiryDate = value;
    }

}
